spring:
  datasource:
    url: jdbc:postgresql://prod-db-server:5432/customerdb_prod
    username: prod_user
    password: ${DB_PASSWORD}   # Read from environment variable for security
    driver-class-name: org.postgresql.Driver

logging:
  level:
    root: WARN
