spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/customerdb_local
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

logging:
  level:
    root: DEBUG