spring:
  datasource:
    url: jdbc:postgresql://localhost:30432/postgres
    username: hari
    password: dudkrish1A
    driver-class-name: org.postgresql.Driver

jwt:
  secret: Wo27Rk4IJcuDSAJTdkjTcnWbj/cXFiAyehKEIa+nc+a1OjaFSxttvaCDvtALRluhAN/xrvuVBea8kCGpJolxHw==
  expiration-ms: 7200000  # 2 hour
